### ISSUE TITLE
Data set description template

### ISSUE THREAD

**Issue by memartone** [SciCrunch/sparc-curation#13]
I don't think that the HasNext and HasChildren example in the "Completeness of data set" element will make sense to most researchers.  I suggest that you modify it.

**Comment by tgbugs** [comment]
Agree. We knew they were problematic at the outset, but we didn't have any ideas for what would be clearer other than the full sentence description of each of them. Any suggestions for other more sensible compact forms would be appreciated.

**Comment by memartone** [comment]
How about just:  Is part of;

**Comment by tgbugs** [comment]
Going the other direction we have `has parent` which is basically interchangeable with `part of`, however the relationships we are trying to convey are open because the datasets do not yet exist so there is no referent. Some possibilities I have thought of:
1. `expectSameProtocolWithNewSubjects`
2. `expectDerivedFromSameSubjects`
3. `expectDerivedFromSamples`

**Comment by memartone** [comment]
I think that is way too complicated for a spreadsheet.  I think I would just as them to provide the related data sets + a description of their relationship.

**Comment by tgbugs** [comment]
We can get rid of ways to let people indicate that they are expecting more data, however we will still need a way to allow people to indicate whether their subject/sample ids are the same as in the parent dataset, but we need that anyway. Without the assertion that the ids should match we have to assume that they are different. So maybe we can just replace it with `part of` and make another tag/field available to indicate that "local specimen identifiers refer to the same entities as in the parent dataset".

**Comment by tgbugs** [comment]
@bandrow
