### ISSUE TITLE
Gspread Integration 

### ISSUE THREAD

**Issue by tmsincomb** [SciCrunch/sparc-curation#40]
Replace boilerplate and sheet update with gspread. In large part, this will be future proofing against significant google sheet API updates.

**Comment by tgbugs** [comment]
Changes will need to be made in https://github.com/tgbugs/pyontutils/blob/master/pyontutils/sheets.py.

**Comment by tgbugs** [comment]
Closing since the pyontutils sheets implementation has received a number of bug fixes and avoids additional dependencies. It is still lacking documentation, but that is not a show stopper. At some point we might try to integrate all the various tabular representations to make it easier to interconvert between them, but ideally we would remove the google sheets part of the workflow entirely, so better not to spend any time on this since we want it to go away entirely.
