### ISSUE TITLE
Please provide a link to a sample Cypher query for getting species information about connectivity models

### ISSUE THREAD

**Issue by dbrnz** [SciCrunch/sparc-curation#94]
If nothing else, please provide a TOC and index to the [over 5,500 line document](https://github.com/SciCrunch/sparc-curation/blob/master/docs/queries.org) that may have this information!

**Comment by tgbugs** [comment]
There is a searchable table of contents built in to github (though annoyingly hidden).
![2022-12-19-022654-snip](https://user-images.githubusercontent.com/4299776/208370598-3161c0d1-9676-48c0-b129-f44791659ecd.png)

**Comment by tgbugs** [comment]
I've rebuilt and pushed the ontology docs which include the queries document. http://ontology.neuinfo.org/docs/sparc-curation/docs/queries.html. Those docs pages all come with a table of contents which should be much easier to navigate, as well as a number of other improvements over the janky github rendering, including most importantly fixes to ensure that links resolve.

**Comment by tgbugs** [comment]
I'll drop the link to the query in here once it is written.

**Comment by dbrnz** [comment]
A very much improved queries document, thanks!

**Comment by dbrnz** [comment]
@tgbugs how is the species query going?

**Comment by dbrnz** [comment]
The supplied query ([here](https://github.com/SciCrunch/sparc-curation/blob/079e2529de371faf131e92d84558806ad180fe93/docs/queries.org?plain=1#L3674-L3677)) doesn't return a species for the Keast model, `ilxtr:neuron-type-keast`.

**Comment by tgbugs** [comment]
It will only work for individual neurons. e.g. `ilxtr:neuron-type-keast-5`.

**Comment by dbrnz** [comment]
I did mean `https://apinatomy.org/uris/models/keast-bladder` above...

And the ticket, `Please provide a link to a sample Cypher query for getting species information about connectivity models`, is about getting species information for models, not for individual neurons!

**Comment by tgbugs** [comment]
Models are not annotated with species information because when we went to look there was no easy way to handle a variety of sources and because the actual variability that will need to be rendered is for individual neurons. In other words we assume that a model to species mapping is one to many so we annotate the populations directly (this is not the case for the examples we have right now, but it will be in the future so we have planned accordingly).

In most cases I assume you would have to downward apply any model species information to individual neurons anyway.

If you do want to start from a model you can do so by feeding the results of
https://scicrunch.org/api/1/sparc-scigraph/dynamic/demos/apinat/modelList
https://scicrunch.org/api/1/sparc-scigraph/dynamic/demos/apinat/modelPopulationsReferences/https:%2F%2Fapinatomy.org%2Furis%2Fmodels%2Fkeast-bladder
into the new query for each population.

**Comment by dbrnz** [comment]
Can the individual paths in a model be each derived from different species?

**Comment by tgbugs** [comment]
The plan is to avoid that scenario by encoding all variability the the level of the population. This means that a population will be present or absent in a species as a whole. There might be populations that traverse the same route in two different species and that share a common superclass, but they will be separate individual populations.

**Comment by dbrnz** [comment]
OK, thanks, and after some discussion here, now understood!
