### ISSUE TITLE
Non-existent link in documentation

### ISSUE THREAD

**Issue by dbrnz** [SciCrunch/sparc-curation#95]
In https://github.com/SciCrunch/sparc-curation/blob/master/docs/queries.org the link [cypher-apinat-graphs](https://github.com/SciCrunch/sparc-curation/blob/master/docs/cypher-apinat-graphs) goes to a missing document.

<img width="580" alt="Screenshot 2022-12-20 at 9 42 14 AM" src="https://user-images.githubusercontent.com/239220/208518184-3f7a3630-4bb6-4c4e-b708-709b79b66426.png">

<img width="728" alt="Screenshot 2022-12-20 at 9 42 34 AM" src="https://user-images.githubusercontent.com/239220/208518300-2f773310-2e9c-4b41-bc75-0c415488dce6.png">

**Comment by tgbugs** [comment]
Fixed in the properly built documentation http://ontology.arachne.olympiangods.org/docs/sparc-curation/docs/queries.html#apinat-models. GitHub hasn't the faintest ideas what to do with internal fuzzy links in org documents. I deal with similar links systematically now, so hopefully this won't pop up again.
